# Generated by Django 5.0.1 on 2024-01-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('salary', models.IntegerField(default=1000)),
                ('role', models.CharField(choices=[('C', 'مدیر عامل'), ('E', 'کارشناس'), ('M', 'مدیر')], default='C', max_length=1)),
            ],
        ),
    ]
