name: Test

on:
  push:
    branches:
    - master
  pull_request:


jobs:
  unit-test:
    name: Python ${{ matrix.python-version }} - Django ${{ matrix.django-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']
        django-version: ['3.2', '4.1', '4.2', 'main']
        exclude:
          - python-version: '3.11'
            django-version: '3.2'
          - python-version: '3.12'
            django-version: '3.2'
    steps:
      - uses: actions/checkout@v2
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: texlive-xetex google-chrome-stable
          version: 1.0
      - name: Add persian fonts
        run: |
          mkdir -p ~/.fonts
          cp ./tests/fonts/Vazirmatn.ttf ~/.fonts/
          fc-cache -f -v
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade tox tox-gh-actions
      - name: Tox tests
        run: |
          tox -v
        env:
          DJANGO: ${{ matrix.django-version }}